FROM node:20-slim

# Installer Cloud SQL Proxy
RUN apt-get update && apt-get install -y wget && rm -rf /var/lib/apt/lists/*
RUN wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O /usr/local/bin/cloud_sql_proxy
RUN chmod +x /usr/local/bin/cloud_sql_proxy

WORKDIR /app

# Copier les dépendances
COPY App/package*.json ./
RUN npm install

# Copier le script de migration
COPY migrations/migrations.js .

CMD ["node", "migrations.js"]
